environment:
  matrix:
    # node.js
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "11"
    - nodejs_version: "12"
    - nodejs_version: "13"
    - nodejs_version: "14"
    - nodejs_version: ""

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version

test:
  - npm run lint
  - npm run test:single
  - npm run test:subdomain

build: off

version: "{build}"
